### ISSUE TITLE
Overriding yaml from cli

### ISSUE THREAD

**Issue by louis030195** [google-github-actions/deploy-cloudrun#450]
### TL;DR

I have some env var that is determined during my github action that i want to set using cli instead of the yaml

ref: https://github.com/different-ai/embedbase/blob/6088bf403de577107d7f3509e93b4898f20a74bc/.github/workflows/release_hosted.yml#L102

(ignored atm)

### Detailed design

I'm setting Sentry.io release number during workflow

### Additional information

Workaround: github action do a sed on the yaml before deploying

**Comment by sethvargo** [comment]
Hi @louis030195 - when using a metadata.yaml, all other inputs are ignored as shown in the README:

> **⚠️ When using a custom metadata YAML file, all other inputs are ignored!**

So this is working as intended. We went down this road with the AppEngine action (parsing the user-supplied YAML and injecting select values), but the merge logic turns out to be a nightmare permutation problem (e.g. what happens if the same envvar is defined in the metadata, which takes precedence? how do you _delete_ a envvar from the metadata?). Given our experience there where it's impossible to find a set of solutions that works for all use cases, we decided that deploy-cloudrun will not do any modifications to the metadata yaml file if provided.
